### ISSUE TITLE
Trouble Running Example Script with Custom Model in Conda Environment on Windows 10

### ISSUE THREAD

**Issue by Gerkinfeltser** [Chaoses-Ib/ComfyScript#23]
Hello,

Firstly, I want to express my gratitude for the effort and dedication you've put into developing this project. It's evident that it holds substantial promise. However, I've encountered some challenges while attempting to execute scripts.

I followed the installation process outlined for ComfyScript using the "Package and nodes with ComfyUI" method, opting for a standalone (non-portable) version of comfyui. For your information, my setup involves running comfy within a conda environment on a Windows 10 system.

I attempted to run the example script provided in the README.md file of the repository, making a minor modification to use a different model that I possess. You can find the script I used here: [test.py.txt](https://github.com/Chaoses-Ib/ComfyScript/files/14234583/test.py.txt).

Encountering errors, I've captured and shared the log for your review: [ComfyScript.log](https://github.com/Chaoses-Ib/ComfyScript/files/14234586/ComfyScript.log).

Could you offer any guidance or suggestions on how to resolve these issues and successfully run the script? Any advice would be greatly appreciated.

Thank you for your support.

**Comment by Chaoses-Ib** [comment]
Have you tried to load with another ComfyUI server? i.e. start ComfyUI manually, and then
```python
from comfy_script.runtime import *
load('http://127.0.0.1:8188/')
from comfy_script.runtime.nodes import *
```

**Comment by Chaoses-Ib** [comment]
This bug is now fixed. Thanks for your report. Please run `git pull` to update and try again.

**Comment by Gerkinfeltser** [comment]
Awesome! Thanks for the quick fix! I'm still getting errors upon running the script but the image gets generated!

Here's the log (using exact same script as above). Again, while the errors are annoying, it works.
[comfyui.log](https://github.com/Chaoses-Ib/ComfyScript/files/14240693/comfyui.log)

Thanks again!

**Comment by Chaoses-Ib** [comment]
The remaining errors are all about some special custom nodes. You can use other nodes normally. I'll fix there errors one by one, but that may take several days to finish. If there are nodes you want to use in them, you can comment here and I'll fix them first.

FYI, here is a list of broken nodes in your log:
```python
0246.ScriptRule
0246.ScriptPile
List of any [Crystools]
XY Input: Lora Block Weight //Inspire
LoraLoaderBlockWeight //Inspire
Reorder
ModelFinder
CombineJobs
GetJobStep
JoinImageBatch
JoinImages
FaceStyler
MaterialsStyler
ComfyUIStyler
FaceStylerAdvanced
MaterialsStylerAdvanced
ComfyUIStylerAdvanced
ttN xyPlot
Qr Code (mtb)
Text To Image (mtb)
HighRes-Fix Script
```

**Comment by Chaoses-Ib** [comment]
Wow, [comfyui-styles-all](https://github.com/aegis72/comfyui-styles-all) adds ~500k values to the value list, that's crazy... So much values make loading too slow. I need to do some optimizations, or ignore too large lists.

**Comment by Gerkinfeltser** [comment]
Awesome, thanks again for looking into this! I super appreciate it & am sorry for the extra work!
